### ISSUE TITLE
Failed to launch on Debian10/x64 machine.

### ISSUE THREAD

**Issue by seamt** [pkgforge-dev/PPSSPP-AppImage#7]
Dear devs:

On my old SONY laptop, it just cannot be launched, The error messages in console are:
```
Ignoring invalid max threads value 4294967295 > max (100000).
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
Vulkan library loaded ('libvulkan.so')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 24
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000002)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_drm_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (0000000a)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000002)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_headless_surface (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_surface_maintenance1 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_swapchain_colorspace (00000005)
VulkanMaybeAvailable: Instance extension found: VK_KHR_portability_enumeration (00000001)
VulkanMaybeAvailable: Instance extension found: VK_LUNARG_direct_driver_loading (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Failed to count physical devices (VK_ERROR_INITIALIZATION_FAILED)
VulkanMayBeAvailable: Destroying instance
Vulkan with working device not detected.
DEBUG: Vulkan is not available, not using Vulkan.
Info: We compiled against SDL version 2.30.1, but we are linking against SDL version 2.30.9., be aware that this can lead to unexpected behaviors
ThreadManager::Init(compute threads: 4, all: 8)
58:36:598 Core/Config.cpp:365 I[G3D]: Longest display side: 1366 pixels. Choosing scale 2
58:36:619 UI/BackgroundAudio.cpp:519 E[SYSTEM]: Failed to load the default sample for UI sound 5
58:36:619 UI/BackgroundAudio.cpp:519 E[SYSTEM]: Failed to load the default sample for UI sound 6
58:36:619 UI/NativeApp.cpp:320 E[LOADER]: Failed graphics backends: OPENGL
SDL_CreateWindow failed for GL 4.6: Couldn't find matching GLX visual
SDL_CreateWindow failed for GL 4.6: Couldn't find matching GLX visual
...
SDL_CreateWindow failed: Couldn't find matching GLX visual
GL init error ''
SDL: Trying a different audio device
Failed to open audio device: Audio subsystem is not initialized
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!

```

App version: 1.17.1-1
https://github.com/pkgforge-dev/PPSSPP-AppImage/releases/tag/1.17.1-1

Hardware info:
```
$ lspci |grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation GT218M [GeForce 310M] (rev a2)
01:00.1 Audio device: NVIDIA Corporation High Definition Audio Controller (rev a1)

```

The GPU (GeForce 310M) support OpenGL 3.3, and has no VULKAN feature.
On the same machine (dual OS installed), official PPSSPP 1.18.1 build for Windows can run very well on Windows 10/x64.

Could you kindly give a look for it?

**Comment by Samueru-sama** [comment]
It seems the version of OpenGL your GPU supports is too old for this. 

Looking for the error I found this similar issue with the flatpak of PPSSPP: https://forums.linuxmint.com/viewtopic.php?t=350665

Do you have this issue with the flatpak of PPSSPP?

**Comment by seamt** [comment]
As far as I can remember, the flatpak version of PPSSPP also fail on my Debian10/x64.
But the libretro core PPSSPP (version 48aa41e, downloaded form libretro/RetroArch official site), wokr well under Retroarch 1.7.3, Debian10x64.
So it seems the limitation is not due to PPSSPP and my GPU, but the build environment of AppImage/flatpak. Is that right?

**Comment by Samueru-sama** [comment]
> As far as I can remember, the flatpak version of PPSSPP also fail on my Debian10/x64. But the libretro core PPSSPP (version 48aa41e, downloaded form libretro/RetroArch official site), wokr well under Retroarch 1.7.3, Debian10x64. So it seems the limitation is not due to PPSSPP and my GPU, but the build environment of AppImage/flatpak. Is that right?

The issue is that the OpenGL version that ships with the PPSSPP binary in both the flatpak and this AppImage (this AppImage ships its own OpenGL and Vulkan) is too new for your GPU, so it can't work. 

There isn't much that I can do since I just take the PPSSPP binary from Archlinux and turn it into an AppImage, it would need some considerable work to instead build PPSSPP manually and then find a way to allow an older version of OpenGL to be bundled. 

With this said there are some other PPSSPP AppImages that rely on the OpenGL of your distro and might work for you, like this one: https://github.com/mantralunar/ppsspp

But you might run into a separate issue: Since that AppImage depends on the host dependencies, if it was built on a distro that is newer than Debian 10 (which is very likely) you will likely get some glibc symbol errors and not be able to launch the AppImage. 

So there isn't much that can be done, I do have plans to compile manually PPSSPP and will see what I can do about this, but that's going to be much later since I've been busy lately with other stuff.
